---
# tasks file for prerequisite
- name: Check if directory exists
  stat:
    path: /var/lib/ansible
  register: dir_check

- name: Clone repository
  git:
    repo: "{{ repo_url }}"
    dest: /var/lib/ansible
  when: not dir_check.stat.exists

- name: Replace IP address in Prometheus config file
  replace:
    path: /var/lib/ansible/prometheus.yml
    regexp: '(\d{1,3}\.){3}\d{1,3}'
    replace: '{{ public_ip }}'
