---
# tasks file for node-exporter
- name: Run Node Exporter container
  docker_container:
        name: node-exporter
        image: prom/node-exporter
        restart_policy: always
        network_mode: host
        publish_all_ports: true
