version: '3'

services:
  blackbox-exporter:
    image: prom/blackbox-exporter
    restart: always
    ports:
      - "9115:9115"
    volumes:
      - /var/lib/blackbox.yml:/etc/blackbox_exporter/blackbox.yml

  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - /var/lib/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
