---
- name: Install Docker, Clone GitHub repo, and Replace IP address in Prometheus config
  hosts: all
  become: true
  vars:
    public_ip: "{{ lookup('pipe', 'curl -s ifconfig.me/ip') }}"
    repo_url: https://github.com/imjerri/ansible-prometheus.git
  tasks:
    - name: Install Docker
      package:
        name: docker-ce
        state: present
      when: ansible_pkg_mgr == 'apt' or ansible_pkg_mgr == 'yum'

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'
      when: ansible_pkg_mgr == 'apt' or ansible_pkg_mgr == 'yum'

    - name: Clone repository
      git:
        repo: "{{ repo_url }}"
        dest: /var/lib/ansible

    - name: Replace IP address in Prometheus config file
      replace:
        path: /var/lib/ansible/prometheus.yml
        regexp: '(\d{1,3}\.){3}\d{1,3}'
        replace: '{{ public_ip }}'

    - name: Run Docker Compose
      docker_compose:
        project_src: /var/lib/ansible/docker-compose.yml
        project_name: my_project
        state: present
