---
- name: Install Docker, Clone GitHub repo, and Replace IP address in Prometheus config
  hosts: all
  become: true
  vars:
    public_ip: "{{ lookup('pipe', 'curl -s ifconfig.me/ip') }}"
    repo_url: https://github.com/imjerri/ansible-prometheus.git
  tasks:
    - name: Install Docker
      package:
        name: docker-ce
        state: present
      when: ansible_pkg_mgr == 'apt' or ansible_pkg_mgr == 'yum'

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'
      when: ansible_pkg_mgr == 'apt' or ansible_pkg_mgr == 'yum'

    - name: Check if directory exists
      stat:
        path: /var/lib/ansible
      register: dir_check

    - name: Clone repository
      git:
        repo: "{{ repo_url }}"
        dest: /var/lib/ansible
      when: not dir_check.stat.exists

    - name: Replace IP address in Prometheus config file
      replace:
        path: /var/lib/ansible/prometheus.yml
        regexp: '(\d{1,3}\.){3}\d{1,3}'
        replace: '{{ public_ip }}'

    - name: Change to Docker Compose directory and start the Compose file
      become: true
      command: docker compose up -d
      args:
        chdir: /var/lib/ansible
