global:
  scrape_interval:
scrape_configs:

  - job_name: 'promndnode'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090','65.2.148.233:9100']

  - job_name: 'blackbox_exporter'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://maia-care.com
        - https://assessmentservice.dev.maia-care.com/admin
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 65.2.148.233:9115