---
      - name: Install Docker
        package:
          name: docker-ce
          state: present
        when: ansible_pkg_mgr == 'apt' or ansible_pkg_mgr == 'yum'

      - name: Install Docker Compose
        get_url:
          url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
          dest: /usr/local/bin/docker-compose
          mode: 'u+x,g+x'
        when: ansible_pkg_mgr == 'apt' or ansible_pkg_mgr == 'yum'
