---
# tasks file for blackbox-exporter
- name: Create BlackBox-Exporter directory 
  file:
    path: /etc/blackbox_exporter
    state: directory  

- name: Install Blackbox Exporter
  docker_container:
    name: blackbox
    image: prom/blackbox-exporter
    state: started
    restart_policy: always
    ports:
      - "9115:9115"
    volumes:
      - /home/ubuntu/blackbox/blackbox.yml:/etc/blackbox_exporter/blackbox.yml

